name: gcc

on:
  push:
    branches: [ main, fix/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - g++-11
          - g++-12
          - g++-13
          - g++-14
        build_type: [ Debug, Release ]
        include:
          # gcc-11 doesn't support constexpr vector and string, so there is no point in attempting to build with it
          - runner: ubuntu-22.04
            compiler: g++-11
            dont_use_std_vector: ON
            dont_use_std_string: ON
          # gcc-12's constexpr string implementation has bugs: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105440
          - runner: ubuntu-22.04
            compiler: g++-12
            dont_use_std_string: ON
          # gcc-13's constexpr string implementation has bugs: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105440
          - runner: ubuntu-24.04
            compiler: g++-13
            dont_use_std_string: ON
          # gcc-14's constexpr string implementation still has bugs: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105440
          - runner: ubuntu-24.04
            compiler: g++-14
            dont_use_std_string: ON

    runs-on: ${{matrix.runner}}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S test/ -B ${{github.workspace}}/build
          -D CMAKE_BUILD_TYPE=${{matrix.build_type}}
          -D BUGSPRAY_DONT_USE_STD_VECTOR=${{matrix.dont_use_std_vector}}
          -D BUGSPRAY_DONT_USE_STD_STRING=${{matrix.dont_use_std_string}}
          -D CMAKE_CXX_COMPILER=${{matrix.compiler}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}} --test-dir ${{github.workspace}}/build --output-on-failure
      
